In [1]:
import pandas as pd

In [3]:
load = pd.DataFrame.from_csv('test_data/LoadedHighway_Fare.csv')
load.reset_index(drop=True,inplace=True)

In [5]:
load.head()

,A,B,DISTANCE,SPDCLASS,CAPCLASS,LANES,TSIN,GL,USE,OT,...,VOLT_DA,VOLT_S2,VOLT_S3,VOLT_SM,VOLT_HV,VOLT_DAT,VOLT_S2T,VOLT_S3T,VOLT_SMT,VOLT_HVT
0,1,7487,0.05201,6,6,7,1,1,1,0.17337,...,1799.45581,225.49336,120.30231,518.76355,102.39098,34.50405,4.88058,0,6.48032,0
1,1,7489,0.04758,6,6,7,1,1,1,0.15860,...,888.10297,402.70639,240.12395,265.88324,43.53552,60.17905,23.63567,0,5.93069,0
2,2,7496,0.06356,6,6,7,1,1,1,0.21187,...,1112.16333,640.49030,399.05765,451.72116,73.73388,72.14450,41.95911,0,10.65161,0
3,2,7500,0.05204,6,6,7,1,1,1,0.17347,...,3263.00537,343.76221,225.27765,745.93463,152.05202,51.77525,0.07324,0,7.91159,0
4,3,7483,0.12645,6,6,7,1,1,1,0.42150,...,313.39093,70.63329,28.50105,34.58564,5.85082,0.09533,0.00216,0,0.03485,0